### PR TITLE
Improving .select(...) method to allow OR queries

### PR DESCRIPTION
**Pull request by urpizu**
Moreover, code has been refactored.

### CODE REVIEW

**Review by glecko — APPROVED** [review]
Love it! :D

**Review by philippe2803 — CHANGES_REQUESTED** [review]
I'm unsure about this code.
I'm under the impression it could consider item to be matching the filters, although it found some labels that were not matching.

Also, it will be insanely slower from a speed performance (and not because we check multiple elements).

The reason we start with the variable "matching" as True instead False (and break out of the loop when not matching) is to prevent checking if some other labels are matching when we know one did not match already. If one label is not matching, no point in checking if the other labels are matching or not. From the moment we find a label not matching the filters, we skip it and go to the next item.


I think we could simply use the original code, with an extra if/else workflow. See comment below.

EDIT: Also, I may be wrong but in case of filters with multiple labels. If the first label does not match, but the next label does match, it looks as if the whole item will be considered matching, although this is not case.

**Comment by philippe2803** [comment]
This is how I think it could be done. Adding a new function as follow:

```javascript
function isMatchingLabel(value, filter) {
  if (Array.isArray(filter)) {
    if(filter.indexOf(value) < 0) {
      return false
    }
  } else {
    if(value !== filter) {
      return false
    }
  }
  return true
};

```

Add some more code to it so it handles the Date instances properly. You can then add it to the original select method (starting with matching as true) and I think you get something clean and faster.

**Comment by urpizu** [comment]
Hey @philippe2803, all misunderstanding came from presuming the original select was an OR.

With the last commit, the new select is an AND by default. Is adding features as selecting by OR, and AND with ORs inside. Moreover, all values could be dates.

I tested next cases, all of them working successfully:
```
{name: 'Guillem', surname: 'Orpinell'} // (name === 'Guillem' && surname === 'Orpinell')
{assigneeId: ['GO','AM']} // (assigneeId === 'GO' || assigneeId === 'AM')
{color: 'red', tags: [1, 2], operator: 'OR'} // (color === red || tags === 1 || tags === 2)
{date: today, tags: [1, 2]} // (dateFrom === today && (tags === 1 || tags === 2))
```

Thanks @glecko for the help in the definition and debugging 👯

**Comment by philippe2803** [comment]
I'm not a fan of pushing the capabilities of the select method personally. I feel this is overkill for the scope of this library, and doubt this will make the code easier to read and/or maintain. Happy to discuss it in more depth though.

If this is a path we decide to take with the library, this needs to be properly organised, and the syntax we implement should be decided together. Due to how complex a query can be and in order to keep the code clean and organised, this should be dealt with a Select or Selector class for example.

We should look at the MongoDb syntax for inspiration, on how they deal with and, or, gt, lt, etc...

As it is now, I find the code uneasy to follow, and it's probably worth creating a select.gs file to put every method and functions we use for this feature.

**Comment by urpizu** [comment]
So, as we discussed, in the new commit you can see the selector constructor with the CNF logic. It's been tested and works like a charm! Moreover, it's 100% compatible with previous versions =) Thanks @sp-jordi-miro for the input!

PS: In order to rebase, I asked for help to @sp-ricard-valverde. We needed rewrite the commits and we did it with his git; that's why he appears as the author ;)

**Review by sp-jordi-miro — APPROVED** [review]

**Review by philippe2803 — APPROVED** [review]

**Comment by philippe2803** [comment]
It looks very good. I really like it.

**Pull request merged**
