### PR TITLE
Allow .add method to also accept Item() instances

### PR DESCRIPTION
**Pull request by glecko**
I think this is a useful method to have, to get an item as a plain javascript object in a {header: fieldValue} pair style, which you can easily loop through with for(var i in object)

### CODE REVIEW

**Comment by sp-guillem-orpinell** [comment]
Uhm.... I'm using 
` for (var field in item.fields) { 
     var value = item.getFieldValue(field);
}` 
and I think it's basically what you intend to do! Doesn't it?

**Comment by glecko** [comment]
Yes exactly. The point is that when you want to move an item from one table to another, until now you have to build the object by yourself in the way you say.

With this method (which is really small), the code becomes the following:

`var item = table.select(...).first();
anotherTable.add(item.toObject))`

**Comment by sp-guillem-orpinell** [comment]
Then i'd approach it as an .add method extension, so it can allow raw items and "rich" items ;)

**Comment by glecko** [comment]
Completelly true, I changed the scope of the PR =)

**Review by sp-guillem-orpinell — APPROVED** [review]
Awesome!

**Pull request merged**
